name: ClockIn

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: 0 */8 * * *

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.9
      - name: Install packages
        run: |
          pip3 install requests
          pip3 install ddddocr
      - name: Clock In Haowei
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python3 clock-in.py ${ACCOUNT} ${PASSWORD} ${EAI_SESS}
      - name: Clock In GuoLing
        env:
          ACCOUNTGL: ${{ secrets.ACCOUNTGL }}
          PASSWORDGL: ${{ secrets.PASSWORDGL }}
        run: |
          python3 clock-in.py ${ACCOUNTGL} ${PASSWORDGL} ${EAI_SESS}          
      - name: Clock In Tianxing
        env:
          ACCOUNTHTX: ${{ secrets.ACCOUNTHTX }}
          PASSWORDHTX: ${{ secrets.PASSWORDHTX }}
        run: |
          python3 clock-in.py ${ACCOUNTHTX} ${PASSWORDHTX} ${EAI_SESS}         
      - name: Clock In Xiaochuan
        env:
          ACCOUNTNXC: ${{ secrets.ACCOUNTNXC }}
          PASSWORDNXC: ${{ secrets.PASSWORDNXC }}
        run: |
          python3 clock-in.py ${ACCOUNTNXC} ${PASSWORDNXC} ${EAI_SESS}             
